spring.application.name=tester
spring.datasource.url=jdbc:postgresql://localhost:5432/vstutestingsystem
spring.datasource.username=postgres
spring.datasource.password=TimBD

spring.jpa.hibernate.ddl-auto=update